Proofreading.
hbeni/fgcom-mumble pull request #111
Opened 2021-05-05 16:04 UTC by MariuszXC

Some language cleanup.
References to files modified to reflect the directory structure as delivered to the user.  Had to sacrifice navigation in source tree in order. Don't see an easy way around it, unless splitting main README.md into short generic intro (with in-tree working links) and e.g. README-plugin.md meant for asset inclusion (and perhaps a similar README-server.md for server-side docs).

2021-05-05 21:30 UTC, hbeni commented
> References to files modified to reflect the directory structure as delivered to the user.  Had to sacrifice navigation in source tree in order. Don't see an easy way around it.

There is an easy way around it: I include this replacements dynamically in the build scripts.
I would really want to let the links intact for easy github browsing.
Good catch, i will add that - can you please revert those links?

2021-05-06 08:37 UTC, MariuszXC commented
Links reverted to original state.
Two point to server part of the tree. Probably candidates for dynamic removal in build?

2021-05-06 08:59 UTC, hbeni approved these changes

2021-05-06 13:24 UTC, hbeni requested changes

2021-05-06 13:24 UTC, hbeni commented on README.md
> -Note that frequencies can be arbitary strings. That said, all participating clients must share a common definition of "frequency", this should be the physical radio wave frequency in MHz and not the
The two spaces at the end of the line is Markdown syntax (linebreak) and I added them purposely so the online formatting is better.
I noticed several occasions where you removed those two spaces - was that just to clear up or do you really want to change the formatting?

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> +The [new protocol xml-file](fgfs-addon/FGData/Protocol/fgcom-mumble.xml) is supplied in the source tree and documented (`client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml`).
I think you forgot this instance in your recent revert :)
I think it now should read `client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml`

2021-05-06 13:24 UTC, hbeni commented on README.md
> -The release ZIP contains all binary plugins for all supported operating systems in the `mumble-plugin` folder:
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on README.md
> +FGCom-mumble releases ship with a cross-plattform java application that implements most of the UDP protocol and thus can be used not only for testing purposes, but also real operations without the ne
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on README.md
> +After starting flightgear, you can use your radio stack like with FGCom (default is *space* to talk on COM1 and *shift+space* for COM2).
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on README.md
> +For better FGCom-mumble support, [patches are already pending](https://sourceforge.net/p/openradar/tickets/) and there is a [binary package available](http://fgcom.hallinger.org/OpenRadar_fgcom-mumbl
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on README.md
> +Note: Chances are good that your ATC client does all this for you and you just need to push some "Record ATIS" button.
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on README.md
> +The FGCom-mumble client plugin needs to be in binary form. If you want to use the latest code from github, you can compile yourself. The makefile is tailored to be used mainly on linux, but can be us
This one is good :+1:

2021-05-06 13:24 UTC, hbeni commented on README.md
> +The makefile works well on Windows with cygwin64 with mingw32.
ok

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> -If a users fgcom mumble plugin then receives a new audio transmission, it will:
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> -Then, if the frequency is currently tuned AND the sender was in radio-range AND the current user is not transmitting himself on the frequency in question, the received transmision will be played; oth
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> +To send data to the plugin, flightgear must be started with property-tree synchronization trough a generic protocol.
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> -You can establish virtual land lines by adding a new "virtual radio" with a special custom frequency starting with `PHONE` like "PHONE-EDDM-TWR". Such connections are not subject to radio signal qual
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> -Volume settings and operational state of the simulated phone is applied, however.
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> -This can be easily supported trough a special `radio-recorder` bot that will listen for incoming record requests over the mumble plugin API.
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> -Recording has to be done using a special frequency like `RECORD_<tgtFreq>`. The other pilots will not hear the recording, because they can't tune into this frequency. Just the `radio-recorder` bot wi
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on Readme.architecture.md
> -For user convinience there is also a webpage that shows the current status.
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on client/fgfs-addon/Readme.md
> -After unzipping the FGCom-mumble release package, you just need to add the `fgfs-addon` folder to your launchers *Add-ons* module list.
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on client/fgfs-addon/Readme.md
> -If you wish to adjust the parameters, you can access them via the new *Multiplayer* menu entry. This is usually not needed except you are running several mumble instances or mumble not on the same co
Spaces removed? (Markdown syntax)

2021-05-06 13:24 UTC, hbeni commented on client/radioGUI/Readme.RadioGUI.md
> -RadioGUI can connect to a SimConnect compatible simulator like MFSF2020.
Spaces removed? (Markdown syntax)

2021-05-06 13:27 UTC, hbeni commented
> Links reverted to original state.
> Two point to server part of the tree. Probably candidates for dynamic removal in build?

No, i want to keep them mentioned. The build script does remove the links and add "(not included)" in those cases.

2021-05-06 18:48 UTC, MariuszXC commented on README.md
> -Note that frequencies can be arbitary strings. That said, all participating clients must share a common definition of "frequency", this should be the physical radio wave frequency in MHz and not the
Spaces were an oversight on my part. Keep'em.

2021-05-06 18:49 UTC, MariuszXC commented on Readme.architecture.md
> +The [new protocol xml-file](fgfs-addon/FGData/Protocol/fgcom-mumble.xml) is supplied in the source tree and documented (`client/fgfs-addon/FGData/Protocol/fgcom-mumble.xml`).
As you said, two pair of eyes are better than one :)

2021-05-06 18:50 UTC, hbeni commented
Would be easier to merge if the spaces are out.
I can also merge and revert partly, no problem , but i will be not home this weekend

2021-05-06 19:36 UTC, MariuszXC commented on README.md
> +For better FGCom-mumble support, [patches are already pending](https://sourceforge.net/p/openradar/tickets/) and there is a [binary package available](http://fgcom.hallinger.org/OpenRadar_fgcom-mumbl
Keep'em

2021-05-06 21:47 UTC, MariuszXC commented
OK, sorry for the mess. I'll try to prepare one more pull request. I hope I'll repair all.

2021-05-07 20:46 UTC, MariuszXC commented
Found two more places. Hopefully last. 
If you accept, this may be closed?

2021-05-10 06:56 UTC, hbeni commented on Readme.architecture.md
First i was inclined to "hang itself" but that would had indicated a dangling process (kidding)

Honestly, thank you for this, I didn't want to use violent language here but was not able to come up with something better :) :+1:

2021-05-10 06:57 UTC, hbeni approved these changes
Thank you very much for this! Much apprechiated, and sorry for my nagging :)

2021-05-10 06:57 UTC, merged